Fix: libsodium dependency
Error: Package: plesk-php80-sodium-8.0.22-1centos.7.220805.0534.x86_64 (PLESK_17_PHP80)
           Requires: libsodium.so.23()(64bit)
Error: Package: plesk-php81-sodium-8.1.9-1centos.7.220805.0534.x86_64 (PLESK_17_PHP81)
           Requires: libsodium.so.23()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest